entity-test-lib/src/main/java/org/terracotta/passthrough/IMessageSenderWrapper.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnection.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnectionState.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughEntityRef.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughEntityTuple.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughInterserverInterlock.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughLockManager.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessage.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessageCodec.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerMessageDecoder.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java

Note that the work-around for duplicate create/destroy calls is only temporary and will be resolved, more completely, under #16.

Issue 15: Fix duplicate write-lock and entity create/destroy operations

---

entity-test-lib/src/main/java/org/terracotta/passthrough/IClusterControl.java
entity-test-lib/src/main/java/org/terracotta/passthrough/ICommonTest.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughClusterControl.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughTestHelpers.java

-IClusterControl defines how to interact with a stripe from inside a test
-ICommonTest defines a simple yet effective test shape - setup and destroy are done by an over-arching thread or process while the test is run by on potentially different (potentially many) clients
-PassthroughClusterControl is an implementation of IClusterControl to expose the control of a testing stripe built on the passthrough classes
-PassthroughTestHelpers contains some basic helpers for common testing cluster topology setup

Fix #21: Added the basic interfaces and helpers to build tests on the passthrough classes

---

packaging-support/pom.xml
packaging-support/src/main/java/com/tc/classloader/CommonComponent.java
pom.xml
standard-cluster-services/pom.xml
standard-cluster-services/src/main/java/org/terracotta/entity/ClientCommunicator.java
standard-cluster-services/src/main/java/org/terracotta/persistence/IPersistentStorage.java
standard-cluster-services/src/main/java/org/terracotta/persistence/KeyValueStorage.java

Moved CommonComponent from terracotta-core into a new packaging-support module here and updated standard-cluster-services interfaces to reference it.

Issue 28:  Moved CommonComponent to this repository

---

standard-cluster-services/src/main/java/org/terracotta/monitoring/IMonitoringProducer.java

-this represents the starting-point of the service interface which can absorb arbitrary add/remove data element events from any entity or the platform

Fix #30: Add IMonitoringProducer interface to standard-cluster-services

---

connection-api/src/main/java/org/terracotta/connection/entity/EntityRef.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughEntityRef.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughLockManager.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessage.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessageCodec.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerMessageDecoder.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java

-this method is like destroy() but it will fail, instead of blocking, if it can't get the exclusive lock on the entity
-most of the change is updating passthrough to support this

Fix #27: Added tryDestroy to EntityRef API

---

entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughBuiltInServiceProvider.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughCommunicatorServiceProvider.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServiceRegistry.java

-while this produces some nearly duplicated registration paths, it allows greater flexibility in terms of how built-in services can interact with the implementation

Fix #41: Passthrough built-in service providers now implement PassthroughBuiltInServiceProvider

---

entity-test-lib/src/main/java/org/terracotta/entity/PassthroughEndpoint.java
entity-test-lib/src/main/java/org/terracotta/entity/PassthroughStripe.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughBuiltInServiceProvider.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughCommunicatorService.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughCommunicatorServiceProvider.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServiceRegistry.java
standard-cluster-services/src/main/java/org/terracotta/entity/ClientCommunicator.java

-this gives a higher-level meaning than was conveyed by byte[]
-this requires that the ClientCommunicator can access the codec used by the entity

Fix #12: ClientCommunicator now takes EntityResponse as its argument

---

entity-test-lib/src/main/java/org/terracotta/passthrough/IMessageSenderWrapper.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnection.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnectionState.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughInterserverInterlock.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughLifeCycleHandler.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessage.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessageCodec.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerMessageDecoder.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java

-this removes the problematic shouldTolerateCreateDestroyDuplication() work-around to avoid errors in re-sent life-cycle messages
-we now track create/destroy/reconfigure messages so that consistent answers can be give, on re-send

Track transaction history of create/destroy/reconfigure for re-send short-circuit

---

entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughEntityRef.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java

Some fixes to support reconfigure in passthrough.  
* do not take an exclusive lock for reconfigure.  It doesn't need it, MANAGEMENT_KEY exclusive mode provides enough isolation
* Services need to be completely rebuilt on restarts
*  close hook may not need to run after failover

fixes to support reconfigure on clustered map

---

entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java

to avoid having the same client port sequence when using 2 mocked clusters at the same time.
We have a test failing because we have a duplicate local port used for 2 separate cluster instances.
CC @jd0-sag @myronkscott @anthonydahanne

client port is statically incremented for passthrough server

---

entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
monitoring-support/pom.xml
monitoring-support/src/main/java/org/terracotta/monitoring/PlatformClientFetchedEntity.java
monitoring-support/src/main/java/org/terracotta/monitoring/PlatformConnectedClient.java

This PR adds Client PID to PlatformConnectedClient and ClientDescriptor to PlatformClientFetchedEntity. 
With these changes server entities can look up PlatformConnectedClient like this 
1. Server entity looks up **PlatformClientFetchedEntity** using **ClientDescriptor** by iterating through list of **PlatformClientFetchedEntity** available in platform monitoring tree
2. Look up **PlatformConnectedClient** using **clientIdentifier** from **PlatformClientFetchedEntity** found in step 1

Add Client PID to PlatformConnectedClient

---

entity-client-api/src/main/java/org/terracotta/entity/EndpointDelegate.java
entity-test-lib/src/main/java/org/terracotta/entity/PassthroughEndpoint.java
entity-test-lib/src/main/java/org/terracotta/entity/PassthroughStripe.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnection.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughEntityClientEndpoint.java

-this now matches the type sent through ClientCommunicator (which is other end of the pipe - sending messages received here)
-the passthrough implementation is also updated to work this way, even adding some gratuitous encode/decode operations in order to better simulate the network

Fix #45: EndpointDelegate.handleMessage() now takes EntityResponse instead of byte[]

---

entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughClusterControl.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnectionService.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerRegistry.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughTestHelpers.java

-for a PassthroughServer to be reachable via the PassthroughConnectionService, it needs to be registered in the global PassthroughServerRegistry
-the PassthroughServerRegistry is a global because there is no way to pass additional data into the ConnectionFactory to help resolve the server instance (it allows a way to hook into a synthetic name registry - emulating the network)

Fix #80: Created "passthrough" URI and ConnectionService

---

entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnection.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java

-a more complete decision on what exceptions to throw, in these cases, still needs to be made
-this avoids the assertion failure which had been triggered, as a result of a previous change
(if nobody is able to test/merge this, tonight, I will get a local build of EhCache running to verify that this resolves the reported issue, in the morning)

Fix #102: Throw IllegalStateException on closed connection/server

---

entity-test-lib/src/main/java/org/terracotta/passthrough/Assert.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnection.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnectionState.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughEntityRef.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughInterserverInterlock.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessageContainer.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerMessageDecoder.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughTransactionOrderManager.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughWait.java

Note that this required that transaction order is persisted, which can cause substantial slow-downs if a slow IPersistentStorage implementation is installed.

Reconnect is now two-phase and re-sent messages are re-ordered

---

entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughTestHelpers.java
entity-test-lib/src/main/java/org/terracotta/passthrough/SimpleClientTestEnvironment.java

* Adding a very simple IClientTestEnvironment implementation:  This one can be used by passthrough tests
* StripeName should be passed in to the helpers:  This means that the stripe name can be used to generate the cluster URI for the IClientTestEnvironment

Enabling IClientTestEnvironment use in passthrough

---

entity-test-lib/src/main/java/org/terracotta/passthrough/IClusterControl.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughClusterControl.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerMessageDecoder.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughTestHelpers.java

This PR adds support for multiple passives in passthrough framework
- PasshtroughClusterControl controls server start/stop and active transition 
- Removes strong coupling between active and passive 
- Adds crashActive method to IClusterControl to test passive transition

Add multi passive support in passthrough framework

---

pom.xml

Expecting this to fail as the maven artifact is probably not yet public ... propose to not wait though in the current context.

Issue #119 Bump parent pom to version 5.0.0

---

entity-test-lib/src/main/java/org/terracotta/passthrough/IClusterControl.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughClusterControl.java
entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughTestHelpers.java

This updates the IClusterControl and PassthroughTestHelpers interfaces in response to downstream requests (eventually, these testing-only concerns will be handled in a different repo).
Note that I will cut a new release of terracotta-apis once this merges!

Last changes before component release

---

connection-api/src/main/java/org/terracotta/exception/EntityAlreadyExistsException.java
connection-api/src/main/java/org/terracotta/exception/EntityException.java
connection-api/src/main/java/org/terracotta/exception/EntityNotFoundException.java
connection-api/src/main/java/org/terracotta/exception/EntityNotProvidedException.java
connection-api/src/main/java/org/terracotta/exception/EntityVersionMismatchException.java
connection-api/src/main/java/org/terracotta/exception/PermanentEntityException.java

This PR adds
- support to introspect EntityExceptions data
- a constructor to set cause for EntityAlreadyExistsException, EntityNotFoundException, EntityNotProvidedException, EntityVersionMismatchException and PermanentEntityException

Fix #127 - Add support to introspect EntityExceptions data

---

standard-cluster-services/src/main/java/org/terracotta/monitoring/IMonitoringProducer.java

-this provides a mechanism for a proder of monitoring data to rapidly send this data through a lower-overhead, less reliable channel
-the definition of the reliability of this mechanism is left up to the implementation
NOTE:  The implementation of #135 will be made in a different PR since it has an impact on some internal types which will require a little more testing.  It will likely end up being posted before the next release is cut, though.

Fix #134: Added IMonitoringProducer.pushBestEffortsData

---

entity-server-api/src/main/java/org/terracotta/entity/ServiceProvider.java

-this includes an expanded description of threading concerns, when/why certain methods are called, and what a "consumerID" is
NOTE:  This should be harmless to merge but we want to coordinate rebases with outstanding pull requests before we know the order.

(READY TO MERGE) Fix #131: Expanded ServiceProvider Javadoc

---

monitoring-support/src/main/java/org/terracotta/monitoring/PlatformClientFetchedEntity.java
monitoring-support/src/main/java/org/terracotta/monitoring/PlatformConnectedClient.java
monitoring-support/src/main/java/org/terracotta/monitoring/PlatformEntity.java
monitoring-support/src/main/java/org/terracotta/monitoring/PlatformServer.java
monitoring-support/src/main/java/org/terracotta/monitoring/ServerState.java
standard-cluster-services/src/main/java/org/terracotta/monitoring/IMonitoringProducer.java

-this will ensure that future concerns of how to communicate monitoring data between active and passive servers will be possible
-this also required that the standard types defined in monitoring-support be made serializable
-of specific note, this means that PlatformClientFetchedEntity's ClientDescriptor had to be marked transient, since it can't be meaningfully deserialized (it is akin to deserializing a file descriptor).  These should appear in cases where this would matter, however, as these are not created by the passive
-for testing reasons, this also required the addition of hashCode() and equals() methods to these types (with the assumption that only this ClientDescriptor field can be null and only due to its transient nature)

Fix #135: IMonitoringProducer values must be Serializable

---

monitoring-support/src/main/java/org/terracotta/monitoring/PlatformMonitoringConstants.java
standard-cluster-services/pom.xml
standard-cluster-services/src/main/java/org/terracotta/monitoring/IStripeMonitoring.java

* this splits the way that monitoring data moves through the system into explicit "sender" and "receiver" components
* `IMonitoringProducer` is still used by an entity when it wants to send data to the monitoring implementation
* `IStripeMonitoring` is the new interface which must be implemented by the monitoring component in order to receive this data
* the `IStripeMonitoring` implementation will receive all monitoring data from the entire stripe, but only the instance running on the active will be given this information

(DISCUSS) Create IStripeMonitoring interface for receiving monitoring data from a stripe

---

entity-server-api/src/main/java/org/terracotta/entity/ServiceRegistry.java

-this also goes into some detail of how consumerID is used to allow a ServiceProvider to implement a basic namespacing of services but that this is the only implicit namespacing mechanism provided, meaning that an entity uses the same consumerID, no matter how many times it requests the service or who it shares the returned instance with
Posted as a starting-point for discussing these JavaDoc changes. Once we feel as though this change is complete, we can merge it (potentially requiring some rebase since there are related discussions to start, as well).

Fix #138: Clarify the implications of using something from one service in another

---

entity-server-api/src/main/java/org/terracotta/entity/ActiveServerEntity.java
entity-server-api/src/main/java/org/terracotta/entity/CommonServerEntity.java
entity-server-api/src/main/java/org/terracotta/entity/ConcurrencyStrategy.java
entity-server-api/src/main/java/org/terracotta/entity/PassiveServerEntity.java

Posted as a starting-point for discussing these JavaDoc changes.  Once we feel as though this change is complete, we can merge it (potentially requiring some rebase since there are related discussions to start, as well).

(DISCUSS) Fix #144:  Added clarification regarding concurrency keys running life-cycle calls

---

entity-server-api/src/main/java/org/terracotta/entity/PlatformConfiguration.java
entity-server-api/src/main/java/org/terracotta/entity/ServiceProvider.java

* PlatformConfiguration exposes server name currently
* Pass PlatformConfiguration to ServiceProviders via initialize(...)

Fix #157 - Add API to expose platform config

---

entity-server-api/pom.xml
entity-server-api/src/main/java/org/terracotta/entity/EntityServerService.java
entity-server-api/src/main/java/org/terracotta/entity/ExecutionStrategy.java
monitoring-support/pom.xml
standard-cluster-services/pom.xml

Added reconfigure to EntityServerService so that implementors have an opportunity to transfer state of the entity to new reconfigured entity since reconfigure happens in the middle of entity execution.
Added ExecutionStrategy to deprecate `InvocationBuilder.requiresReplication()` since that call is mis-placed and mis-used by the platform.
Updated the pom files to reflect that the server is java 1.8 only.

API changes entities

---

standard-cluster-services/src/main/java/org/terracotta/persistence/IPersistentStorage.java
standard-cluster-services/src/main/java/org/terracotta/persistence/IPlatformPersistence.java
standard-cluster-services/src/main/java/org/terracotta/persistence/KeyValueStorage.java

-this new interface is much smaller and more directly aimed at providing high-performance solutions to the platform's persistence needs
-IPersistentStorage and KeyValueStorage can be removed, in a future release, as they are now deprecated

Fix #169: Create new IPlatformPersistence to replace IPersistentStorage

---

standard-cluster-services/src/main/java/org/terracotta/entity/IEntityMessenger.java

-these new interfaces will allow an entity to send itself a specific message after a delay or periodically
-a ScheduledToken is provided so that these calls can be cancelled
NOTE:  This can be merged once we are ready to release.

(READY) Fix #158: Add delayed/periodic calls to IEntityMessenger

---

connection-api/src/main/java/org/terracotta/exception/EntityConfigurationException.java
entity-server-api/src/main/java/org/terracotta/entity/ConfigurationException.java
entity-server-api/src/main/java/org/terracotta/entity/EntityServerService.java

ConfigurationException added to EntityServerService so that implementations can throw on failed lifecycle operations.  The implementations of this API should report EntityConfigurationException back to the client if all nodes of a stripe agree.  If some succeed and others fail, the succeeding servers will survive and failing servers will be zapped.

Fix #181 - add configuration exceptions to lifecycle operations

---

connection-api/src/main/java/org/terracotta/connection/entity/EntityRef.java

This rationalizes a few of the missing exceptions in the EntityRef API.
NOTE:  We should only merge this when we are ready to do the release.

Apis issue 185

---

connection-api/src/main/java/org/terracotta/exception/EntityConfigurationException.java
connection-api/src/main/java/org/terracotta/exception/EntityUserException.java
connection-api/src/main/java/org/terracotta/exception/ServerSideExceptionWrapper.java

This should eliminate the case where we couldn't deserialize server-only exceptions on the client (since we will now only send this type).

Issue 190:  Created new exception type which is just used in place of server-side exceptions

---

entity-server-api/src/main/java/org/terracotta/entity/CommonServerEntity.java

-this allows configuration to be validated when the entity knows whether it is new or old, instead of just at the point of instantiation

Fix #196: CommonServerEntity.createNew() now throws ConfigurationException

---

connection-api/src/main/java/org/terracotta/connection/entity/Entity.java
entity-client-api/src/main/java/org/terracotta/entity/EntityClientService.java

-this is purely a documentation change to describe more of the interactions between Entity and EntityClientEndpoint via the user-provided EntityClientService

Fix #198: Clarify use of EntityClientEndpoint within EntityClientService

---

connection-api/src/main/java/org/terracotta/exception/PermanentEntityException.java
connection-api/src/main/java/org/terracotta/exception/RuntimeEntityException.java

-this was done by creating a new RuntimeEntityException, which is essentially an unchecked clone of EntityException
-PermanentEntityException was reparented to RuntimeEntityException, which can be used as the basis for other such exceptions, in the future

Fix #203: PermanentEntityException is now unchecked

---

connection-api/src/main/java/org/terracotta/exception/ConnectionClosedException.java

-this is an unchecked exception since this shouldn't happen during normal operation
-this should only happen when the client explicitly closes a connection and then tries to use it

Fix #175: Add an exception type to throw when connections unrecoverable

---

connection-api/src/main/java/org/terracotta/connection/Connection.java
connection-api/src/main/java/org/terracotta/connection/entity/EntityRef.java
entity-client-api/src/main/java/org/terracotta/entity/EntityClientService.java

DO NOT MERGE:  Currently posted to check that this makes sense to everyone - release will be required, after merge, to unblock downstream PRs which depend on this.

Fix #202: Added userData argument to EntityClientService.create, from fetchEntity()

---

standard-cluster-services/src/main/java/org/terracotta/entity/ExplicitRetirementHandle.java
standard-cluster-services/src/main/java/org/terracotta/entity/IEntityMessenger.java

Add retirement handles and explicit deferment/retirement to
IEntityMessenger. This is done by deferring retirement of one
message based on another, but not delivering the future message
yet. The returned handle will deliver the future message on it's
release.

Issue 510: Retirement Handles for explicit retirement

---

entity-server-api/src/main/java/org/terracotta/entity/ActiveServerEntity.java
entity-server-api/src/main/java/org/terracotta/entity/CommonServerEntity.java
entity-server-api/src/main/java/org/terracotta/entity/PassiveServerEntity.java

We have mostly decided on, for each invoke (active or passive) passing in the ClientDescriptor (active already did this) and the current and eldest message id. The current is used to track the invoke within the Client, the eldest is used for garbage collection.
Additionally, a new method is added to CommonServerEntity, which notifies at points where the client
view of the data is in synch with the servers. In particular, this would be used when a client disconnects, or when client reconnect happens. At both of these points all historical information related to the client can be thrown away.

[DONT MERGE] Proposal for HA/Message Tracking changes

---

entity-server-api/src/main/java/org/terracotta/entity/ClientDescriptor.java
entity-server-api/src/main/java/org/terracotta/entity/InvokeContext.java

Adds serializable, and isValid(), to ClientDescriptor. Active server services trying to use the message tracking may need to pass ClientDescriptors to passives, so Serializable seems necessary. 
isValid() is merely to represent the fact there exists a NULL implementation that means nothing, seems useful in order to ignore client descriptors that are ersatz.

Issue237: add Serializable to ClientDescriptor

---

entity-common-api/src/main/java/org/terracotta/entity/StateDumpCollector.java

clarify javadoc
change type signature to allow collection of objects.  toString of objects input will be implementation dependent.

Fix state dump api

---

entity-server-api/src/main/java/org/terracotta/entity/InvokeContext.java

There is a need for the invoke context to make the
concurency key available on each invoke.
HEAD merge.

APIS-266: Add concurrency key to InvokeContext (HEAD)

---

entity-server-api/src/main/java/org/terracotta/entity/InvokeContext.java

There is a need for the invoke context to make the
concurency key available on each invoke.
Release 1.3 version.

APIS-266: Add concurrency key to InvokeContext (Release/1.3)

---

connection-api/pom.xml
connection-api/src/main/asciidoc/index.adoc
connection-api/src/test/java/org/terracotta/connection/BasicConnectTest.java
pom.xml

This commit stream includes:
* Recover BasicConnectTest and update connection-api documentation
This commit
* recovers the BasicConnectTest class (used for documentation samples)
* updates Asciidoctor plug-in (dropping need for rubygems:coderay)
* make adjustments to documentation to update for changes over time
* Remove POM repositories elements
This commit reduces the repositories and pluginRepositories elements
to those required to locate the direct dependencies of this project.
More specifically, the SNAPSHOT repositories are removed -- inclusion
of SNAPSHOT repositories interferes with the use of range-based version
specifications.  Should a developer want to include a SNAPSHOT release
in a build, local addition of the SNAPSHOT repositories can be employed.

Remove snapshots
