- entity-server-api/src/main/java/org/terracotta/entity/ServerEntityService.java
- test-entity/server/src/main/java/org/terracotta/TestServerEntityService.java
We will probably rebase this before merging but I figured I would post it just to make sure that nothing else was required (I may amend the commit, or add a new one, if I find more examples of the same problem).
> issue 3: Updated generic type signature to match Active/Passive ServerEntity

- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughCommunicatorServiceProvider.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServiceRegistry.java
This fixes a problem where the in-process test framework couldn't correctly handle service providers which expose more than one interface.
> Issue 23: Removed incorrect service provider registration in PassthroughServiceRegistry

- entity-test-lib/pom.xml
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
- monitoring-support/pom.xml
- monitoring-support/src/main/java/org/terracotta/monitoring/PlatformMonitoringConstants.java
- pom.xml
Note that these are both starting-points, as some corner-cases haven't yet been considered (in in-process) and we are very likely to expand on the defined constants and add types, over time.
> Added monitoring constants and in-process implementation

- entity-test-lib/src/main/java/org/terracotta/passthrough/IMessageSenderWrapper.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnection.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughInterserverInterlock.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughLockManager.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
- monitoring-support/src/main/java/org/terracotta/monitoring/PlatformClientFetchedEntity.java
- monitoring-support/src/main/java/org/terracotta/monitoring/PlatformConnectedClient.java
- monitoring-support/src/main/java/org/terracotta/monitoring/PlatformEntity.java
- monitoring-support/src/main/java/org/terracotta/monitoring/PlatformMonitoringConstants.java
Also uses these in passthrough classes for in-process testing.
> Issue 34:  Introduces the types and constants exposed by platform, to monitoring

- entity-server-api/src/main/java/org/terracotta/entity/MessageCodec.java
- entity-server-api/src/main/java/org/terracotta/entity/MessageCodecException.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
-this gives the MessageCodec implementation a well-defined failure option
> Fix #35: Created MessageCodecException as checked exception for MessageCodec methods

- connection-api/src/main/java/org/terracotta/connection/entity/EntityRef.java
- entity-server-api/src/main/java/org/terracotta/entity/ActiveServerEntity.java
- entity-server-api/src/main/java/org/terracotta/entity/CommonServerEntity.java
- entity-server-api/src/main/java/org/terracotta/entity/MessageCodec.java
- entity-server-api/src/main/java/org/terracotta/entity/PassiveSynchronizationChannel.java
- entity-server-api/src/main/java/org/terracotta/entity/ServerEntityFactory.java
- entity-server-api/src/main/java/org/terracotta/entity/ServerEntityService.java
- entity-test-lib/src/main/java/org/terracotta/entity/PassthroughEndpoint.java
- entity-test-lib/src/main/java/org/terracotta/entity/PassthroughStripe.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughBuiltInServiceProvider.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughCommunicatorService.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughEntityRef.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessage.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessageCodec.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerMessageDecoder.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServiceRegistry.java
- test-entity/server/src/main/java/org/terracotta/TestServerEntity.java
- test-entity/server/src/main/java/org/terracotta/TestServerEntityService.java
Three commits.  
Move codec accessor from active entity to service and change generics type signature.
Move concurrency strategy to service from active entity
Add the ability to reconfigure an entity
> Api refactoring

- entity-server-api/src/main/java/org/terracotta/entity/ServiceProvider.java
- entity-server-api/src/main/java/org/terracotta/entity/ServiceProviderCleanupException.java
Add clear() to ServiceProvider API
> ServiceProvider API change

- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
- monitoring-support/src/main/java/org/terracotta/monitoring/PlatformMonitoringConstants.java
- monitoring-support/src/main/java/org/terracotta/monitoring/PlatformServer.java
Support PlatformServer and additional state information in Passthrough implementation
> Fix #56, Fix #55 - Part 2

- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
Add additional platform monitoring support the the passthrough server implementation.
* Make serverName, bindPort, groupPort settable and deterministic
* Make client remote port ephemeral and unique
> Platform monitoring support

- entity-server-api/src/main/java/org/terracotta/entity/ActiveServerEntity.java
- entity-server-api/src/main/java/org/terracotta/entity/PassiveSynchronizationChannel.java
- entity-server-api/src/main/java/org/terracotta/entity/ServerEntityService.java
- entity-server-api/src/main/java/org/terracotta/entity/ServiceProvider.java
- entity-server-api/src/main/java/org/terracotta/entity/SyncMessageCodec.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
- test-entity/server/src/main/java/org/terracotta/TestServerEntityService.java
> Fix passive sync codec generics and remove closeable on ServiceProvider

- entity-test-lib/src/main/java/org/terracotta/passthrough/IClientTestEnvironment.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/ICommonTest.java
-also converted the ICommonTest interface to accept this and now use the same arguments for all client invocation types
> Created new IClientTestEnvironment interface to provide test environment data to tests

- entity-test-lib/src/main/java/org/terracotta/entity/PassthroughEndpoint.java
- entity-test-lib/src/main/java/org/terracotta/entity/PassthroughStripe.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughBuiltInServiceProvider.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughCommunicatorService.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughCommunicatorServiceProvider.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnection.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughEntityClientEndpoint.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughEntityRef.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughInvocationBuilder.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessageCodec.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessengerService.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughMessengerServiceProvider.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServiceRegistry.java
- standard-cluster-services/src/main/java/org/terracotta/entity/IEntityMessenger.java
Rewords some of passthrough to address warnings and other structural concerns to introduce the passthrough implementation of this interface, as well as the interface, itself.
> Introduce IEntityMessenger

- connection-api/src/main/java/org/terracotta/connection/ConnectionPropertyNames.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
- monitoring-support/src/main/java/org/terracotta/monitoring/PlatformConnectedClient.java
- monitoring-support/src/main/java/org/terracotta/monitoring/PlatformMonitoringConstants.java
Adds the SYNCHRONIZING stage to the server states list.  Servers that are syncing state will be in this stage
Adds uuid as string as a possible connection parameter
Adds name as string as a possible connection parameter
> Add monitoring stage

- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnection.java
If an invoke is issued while handling a server generated message, the passthrough implementation can deadlock due to a lack of thread handling resources.
> Fix #88 - server initiated messages can deadlock passthrough

- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnection.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
* this is now life-cycled along with the server
* also improved use of connection thread names
> Fix leaked PassthroughServer pseudo-connection

- entity-common-api/src/main/java/org/terracotta/entity/StateDumpable.java
- entity-common-api/src/main/java/org/terracotta/entity/StateDumper.java
Services/Entities can use these APIs to dump their state
> Add StateDumpable and StateDumper API

- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
This shouldn't be merged yet - there is another PR we want to see merged, first.
> Fix #95: Call destroy() on the entity, after removing it

- entity-server-api/src/main/java/org/terracotta/entity/ConcurrencyStrategy.java
-this is primarily to make the rule that the implementation must return the same key, for a given message, no matter how many times it is called, more obvious
-also updated some of the other wording to reflect our current types, etc
> Re-word the ConcurrencyStrategy doc

- connection-api/src/main/java/org/terracotta/exception/PermanentEntityException.java
to signal an entity cannot be deleted because it is permanent
> Add new exception type

- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughEntityRef.java
This is to update passthrough server's behavior to emulate what the real server will do after Terracotta-OSS/terracotta-core#227 merges.  They don't create an explicit dependencies but tests which want to run on both will need to wait for both to merge, before being created.
NOTE:  This should probably be rebased and merged _after_ the current set of in-flight PRs.
> Updated passthrough to emulate the new core locking behavior

- entity-client-api/pom.xml
- entity-server-api/pom.xml
- entity-test-lib/pom.xml
- monitoring-support/pom.xml
- test-entity/common/pom.xml
Someone with Maven knowledge:  does this change make sense and seem right?
It was basically some changes I also needed to make along-side the version release.
> Changed internal references to version to properties

- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughConnection.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServer.java
- entity-test-lib/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
Next PR will include a commit which changes some public testing APIs (will isolate that commit in its own PR so that it is more obvious) and will form the basis for the next release
> Did some small clean-up in prepration for API changes

- connection-api/src/main/java/org/terracotta/connection/entity/EntityRef.java
Defines (non-)blocking semantics of the different operations and what
happens when operations are executed concurrently.
> Fix #130 EntityRef API contract updates

- entity-server-api/src/main/java/org/terracotta/entity/ConcurrencyStrategy.java
Posted as a starting-point for discussing these JavaDoc changes. Once we feel as though this change is complete, we can merge it (potentially requiring some rebase since there are related discussions to start, as well).
> Fix #145: Expanded documentation surrounding passive sync

- entity-server-api/src/main/java/org/terracotta/entity/ActiveServerEntity.java
- entity-server-api/src/main/java/org/terracotta/entity/CommonServerEntity.java
- entity-server-api/src/main/java/org/terracotta/entity/PlatformConfiguration.java
- entity-server-api/src/main/java/org/terracotta/entity/ServiceProvider.java
Support configuration objects in PlatformConfiguration
> Fix terracotta-configuration#26 - add support for configuration objects

- connection-api/src/main/java/org/terracotta/exception/PermanentEntityException.java
Permanent entity should extend EntityException
> Fix exception hierarchy

- connection-api/src/main/java/org/terracotta/exception/PermanentEntityException.java
- entity-server-api/src/main/java/org/terracotta/entity/ConfigurationException.java
- entity-server-api/src/main/java/org/terracotta/entity/PlatformConfiguration.java
- entity-server-api/src/main/java/org/terracotta/entity/ServiceProviderCleanupException.java
- entity-server-api/src/main/java/org/terracotta/entity/SyncMessageCodec.java
- standard-cluster-services/src/main/java/org/terracotta/monitoring/IMonitoringProducer.java
- standard-cluster-services/src/main/java/org/terracotta/monitoring/IStripeMonitoring.java
- standard-cluster-services/src/main/java/org/terracotta/monitoring/PlatformService.java
Some small odds-and-ends leading up to the next big release.
> Small changes

- standard-cluster-services/src/main/java/org/terracotta/monitoring/PlatformService.java
expose the raw platform configuration file to PlatformService
> Fix #192 - Expose platform configuration file

- entity-client-api/src/main/java/org/terracotta/entity/InvocationBuilder.java
- entity-client-api/src/main/java/org/terracotta/entity/InvokeFuture.java
(waiting for feedback before merging)
> Fix #200:  Flesh out the details of the acknowledgement system in JavaDoc

- entity-server-api/src/main/java/org/terracotta/entity/ServiceException.java
- entity-server-api/src/main/java/org/terracotta/entity/ServiceRegistry.java
Add a new general checked exception and throw it for getService
> Fix #222 : Fix getService API

- connection-api/src/main/java/org/terracotta/connection/entity/EntityConstructor.java
- connection-api/src/main/java/org/terracotta/exception/EntityServerException.java
- connection-api/src/main/java/org/terracotta/exception/EntityServerUncaughtException.java
- entity-client-api/src/main/java/org/terracotta/entity/InvokeFuture.java
- entity-common-api/src/main/java/org/terracotta/entity/EntityUserException.java
Remove special exception handling for EntityUserException
> Rev exception handling

- entity-server-api/src/main/java/org/terracotta/entity/CommonServerEntity.java
- entity-server-api/src/main/java/org/terracotta/entity/ServiceProvider.java
This change is part of Terracotta-OSS/terracotta-core#551
> Make CommonServerEntity, ServiceProvider extends StateDumpable

- entity-server-api/src/main/java/org/terracotta/entity/ActiveServerEntity.java
- entity-server-api/src/main/java/org/terracotta/entity/CommonServerEntity.java
- entity-server-api/src/main/java/org/terracotta/entity/InvokeContext.java
- entity-server-api/src/main/java/org/terracotta/entity/PassiveServerEntity.java
> Issue 227: rework for context object.

- standard-cluster-services/src/main/java/org/terracotta/entity/IEntityMessenger.java
@ljacomet @AbfrmBlr @chrisdennis - Please review if you find useful or not.
> Add response callbacks to IEntityMessenger API

- connection-api/src/main/java/org/terracotta/connection/ConnectionService.java
- entity-server-api/src/main/java/org/terracotta/entity/ActiveInvokeContext.java
- entity-server-api/src/main/java/org/terracotta/entity/PlatformConfiguration.java
Add default methods to new connection options to make adoption on all lines easier.
> Add default methods to interfaces to make adoption easier

- packaging-support/src/main/java/com/tc/classloader/PermanentEntityType.java
- packaging-support/src/main/java/com/tc/classloader/PermanentEntityTypes.java
- pom.xml
also add permanent entity types
> Parent update

- connection-api/src/main/java/org/terracotta/exception/ConnectionClosedException.java
- packaging-support/src/main/java/com/tc/classloader/TemporaryEntity.java
- standard-cluster-services/src/main/java/org/terracotta/entity/IEntityMessenger.java
- standard-cluster-services/src/main/java/org/terracotta/monitoring/PlatformService.java
multiple additions to the API for new features.  No breaking changes to the current API.
> Api additions

- standard-cluster-services/src/main/java/org/terracotta/monitoring/PlatformService.java
- standard-cluster-services/src/main/java/org/terracotta/monitoring/PlatformStopException.java
@myronkscott These changes are same as the API changes shared by Ramesh earlier. Please review.
> Add PlatformService extensions to implement shutdown primitives

- entity-client-api/src/main/java/org/terracotta/entity/AsyncInvocationBuilder.java
- entity-client-api/src/main/java/org/terracotta/entity/EntityClientEndpoint.java
- entity-client-api/src/main/java/org/terracotta/entity/InvocationBuilder.java
- entity-client-api/src/main/java/org/terracotta/entity/InvocationCallback.java
TC API changes that introduce an async invoker API
> Async Invoker API

- standard-cluster-services/src/main/java/org/terracotta/server/Server.java
Provide a way for any component to write messages to the audit logs of the server.
> support audit logging on the server

- connection-api/src/main/java/org/terracotta/connection/Diagnostics.java
- standard-cluster-services/src/main/java/org/terracotta/server/Server.java
- standard-cluster-services/src/main/java/org/terracotta/server/ServerJMX.java
The server interface needs changes to support embedded server
> add needed server methods

- entity-server-api/src/main/java/org/terracotta/entity/ClientDescriptor.java
- entity-server-api/src/main/java/org/terracotta/entity/ClientSourceId.java
differentiate true clients and server inititated psuedo clients
> add a check to client types 
